.TH minieap 1

.SH NAME
minieap \- Extensible 802.1x client with Ruijie v3/v4 support


.SH SYNOPSIS
.B minieap
.RI [ OPTIONS\fR... ]


.SH DESCRIPTION
.B minieap
can be used as a supplicant for modified 802.1x authentication methods like Ruijie.


.SH OPTIONS

.TP
.BR \-\-help ", " \-h
show help information

.TP
.BR \-\-kill ", " \-k " [0|...]"
kill other instances and exit. args other than 0 means to kill other instances and keeps running.

.TP
.BR \-\-save ", " \-w
save present config

.TP
.BR \-\-username ", " \-u " <\fIusername\fR>"
username

.TP
.BR \-\-password ", " \-p " <\fIusername\fR>"
password

.TP
.BR \-\-nic ", " \-n " <\fIinterface\fR>"
network interface

.TP
.BR \-\-stage-timeout ", " \-t " <\fIsecond\fR>"
timeout for each auth [default is 5]

.TP
.BR \-\-wait-after-fail ", " \-r " <\fIsecond\fR>"
time to wait after fail (but will start immediately if the server ask to) [default is 30]

.TP
.BR \-\-max\-fail ", " \-l " <\fInum\fR>"
max failure times [default is 3]

.TP
.BR \-\-no\-auto\-reauth ", " \-x
do not retry after disconnected [default is yes]

.TP
.BR \-\-daemonize ", " \-b " <0-3>"
0 = run foreground
.br
1 = run as daemon, without output
.br
2 = run as daemon, output to the console
.br
3 = run as daemon, output to the log
.br
[default is 0]

.TP
.BR \-\-proxy\-lan\-iface ", " \-z " <\fIinterface\fR>"
the LAN interface if auth via proxy [default is none]

.TP
.BR \-\-auth\-round ", " \-j " <\fIcount\fR>"
times needs to auth [default is 1]

.TP
.BR \-\-max\-retries " <\fIcount\fR>"
max retry times [default is 3]

.TP
.BR \-\-pid\-file " <\fIpidfile\fR>"
set to none to disable [default is /var/run/minieap.pid]

.TP
.BR \-\-conf\-file " <\fIconffile\fR>"
config file [default /etc/minieap.conf]

.TP
.BR \-\-if\-impl " <\fImodule\fR>"
choose the network module. The option can be only used once. [default is the first available one]

.TP
.BR \-\-pkt\-plugin " <\fIplugin\fR>"
active the corresponding package modifier. The option can be used more than once. [default is none]

.TP
.BR \-\-module " <\fImodule\fR>"
active the corresponding module. The option can be used more than once.

If you use
.B \-\-module
or
.B \-\-pkt\-plugin
in command line, all the lines in config file containing "module=" will be ignored.


.SH Available network modules
.TP
.B sockraw
a module use RAW Socket


.SH Available package modifier
.TP
.B printer
print all the package that go through it

.TP
.B rjv3
use auth algorithm via hyrathb@GitHub Ruijie V3

.RS

.TP
.BR \-\-heartbeat ", " -e " <\fIsecond\fR>"
seconds between packages [default is 60]

.TP
.BR \-\-eap\-bcast\-addr ", " -a " <0-1>"
Start package broadcast address [default BROADCAST_STANDARD]
0 = standard
1 = ruijie's address

.TP
.BR \-\-dhcp\-type ", " -d " <0-3>"
DHCP methods [default HCP_AFTER_AUTH]
.br
0 = don't use DHCP
.br
1 = secondary auth
.br
2 = post\-auth DHCP
.br
3 = pre\-auth DHCP

.TP
.BR \-\-dhcp\-script ", " -c " <\fIscript\fR>"
run script between secondary auth and post\-auth [default is none]

.TP
.BR \-\-rj\-option " <\fItype\fR>:\fI<value\fR>[:r]"
customize sections, the type and value must be in hex.

For example, \fB\-\-rj\-option\fR 6a:000102 means add a section of type 0x6a, with the content of 0x00 0x01 0x02 .

:r means replace the default one generated by this program. For example, \fB\-\-rj\-option\fR 6f:000102:r means to replace the contents of 0x6f type to 0x00 0x12 0x02 .

If the command line and the config file all have this one, both config will work.

.TP
.BR \-\-service " <\fIservice\fR>"
customize service name [default is internet]

.TP
.BR \-\-version\-str " <\fIversion\fR>"
customize version string [default is RG-SU For Linux V1.0]

.TP
.BR \-\-fake\-dns1 " <\fIDNS\fR>"
customize main DNS address (IPv4 in Dotted Decimal Notation) [it will get a address by default]

.TP
.BR \-\-fake\-dns2 " <\fIDNS\fR>"
customize secondary DNS address (IPv4/IPv6)

.TP
.BR \-\-fake\-serial " <\fIserial\fR>"
customize hard disk serial [it will gain by default]

.TP
.BR \-\-max\-dhcp\-count " <\fIcount\fR>"
the times of timeout allowed when second auth wait for DHCP [default is 3]

.RE


.SH SEE ALSO
https://github.com/updateing/minieap


.SH AUTHOR
.PP
The maintainer of minieap is
.MT haotia@\:gmail.com
updateing
.ME .

.PP
This manual page was written by
.MT zouyoo@\:outlook.com
GengYu Rao
.ME ,
for the Debian project (and may be used by others).
